#公共配置 
spring:
  profiles:
    active: dev
  application:
    name: api
  datasource:
    name: era
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    spring.datasource.filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
server:
  port: 8090
  contextPath: /
  tomcat:
    max-threads: 2000
    min-spare-threads: 10
    max-connections: 2000
management:
  security:
    enabled: false
logging:
  file: logs/${spring.application.name}.log
  level:
    root: info
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.hingecloud.apppubs.pub.model

---
#开发环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://apppubs.tpddns.cn:3306/apppubs_pub?characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
    username: hingecloud
    password: hingecloud2018
  servlet:
    multipart:
      max-file-size: 20MB

custom:
  upload:
    dir: upload
    contextPath: upload/
  avatar:
    dir: user-avatar
    contextPath: avatar/
  android:
    prebuildDir: /Users/siger/Developer/apppubs/apppubs-android/
    projectDir: /Users/siger/Developer/apppubs/apppubs-android/apppubs-android/
    resultPath: /Users/siger/Developer/apppubs/apppubs-android/apppubs-android/mportal/build/outputs/apk/release/mportal-release.apk
  ios:
    projectDir: /Users/siger/Developer/apppubs/apppubs-ios/wmh/
    pubsourceDir: /Users/siger/Developer/apppubs/apppubs-ios/wmh/pub/
    resultPath: /Users/siger/Developer/apppubs/apppubs-ios/wmh/build/package/apppubs-release.ipa
  qiniu:
    accessKey: b_P-P5_--nAnU9opyjTJb37aYpkvt66Dq8aZH7nw
    secretKey: mSVLjokAPleEttwgY79fxIrSPakVSMfn6rCCFwpf
    bucket: apppubs
    domain: https://qiniu.apppubs.com/

---
#生产环境
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apppubs_pub?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&allowMultiQueries=true
    username: hingecloud
    password: hingecloud2018
  servlet:
      multipart:
        max-file-size: 20MB

custom:
  upload:
    dir: upload
    contextPath: upload/
  avatar:
    dir: user-avatar
    contextPath: avatar/
  android:
    prebuildDir: /Users/hingesoft/Desktop/build/apppubs-android/
    projectDir: /Users/hingesoft/Desktop/build/apppubs-android/apppubs-android/
    resultPath: /Users/hingesoft/Desktop/build/apppubs-android/apppubs-android/mportal/build/outputs/apk/release/mportal-release.apk
  ios:
    projectDir: /Users/hingesoft/Desktop/build/apppubs-ios/
    pubsourceDir: /Users/hingesoft/Desktop/build/apppubs-ios/pub/
    resultPath: /Users/hingesoft/Desktop/build/apppubs-ios/build/package/apppubs-release.ipa
  qiniu:
    accessKey: b_P-P5_--nAnU9opyjTJb37aYpkvt66Dq8aZH7nw
    secretKey: mSVLjokAPleEttwgY79fxIrSPakVSMfn6rCCFwpf
    bucket: apppubs
    domain: https://qiniu.apppubs.com/